# Generated by Django 4.2.3 on 2023-08-10 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program_Interaction",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "progrmRegistNo",
                    models.CharField(max_length=20, verbose_name="봉사 등록번호"),
                ),
                (
                    "cheered",
                    models.BooleanField(
                        choices=[(True, "True"), (False, "False")], default=False
                    ),
                ),
                (
                    "participated",
                    models.BooleanField(
                        choices=[(True, "True"), (False, "False")], default=False
                    ),
                ),
                (
                    "reviewed",
                    models.BooleanField(
                        choices=[(True, "True"), (False, "False")], default=False
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
