# Generated by Django 4.2.3 on 2023-08-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="program_interaction", old_name="reviewed", new_name="clipped",
        ),
    ]
