# Generated by Django 4.2.3 on 2023-08-14 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("program", "0002_rename_reviewed_program_interaction_clipped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program_interaction",
            name="cheered",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")],
                default=False,
                verbose_name="봉사 응원 여부",
            ),
        ),
        migrations.AlterField(
            model_name="program_interaction",
            name="clipped",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")],
                default=False,
                verbose_name="봉사 스크랩 여부",
            ),
        ),
        migrations.AlterField(
            model_name="program_interaction",
            name="participated",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")],
                default=False,
                verbose_name="봉사 참여 여부",
            ),
        ),
        migrations.AlterField(
            model_name="program_interaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
    ]
