# Generated by Django 4.2.3 on 2023-08-03 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="", verbose_name="리뷰 이미지")),
                ("rid", models.IntegerField(verbose_name="리뷰 rid")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일시"),
                ),
                ("rid", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(verbose_name="리뷰 텍스트")),
                (
                    "progrmRegistNo",
                    models.CharField(max_length=15, verbose_name="봉사 등록번호"),
                ),
                ("category", models.CharField(max_length=60, verbose_name="봉사 카테고리")),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
