# Generated by Django 4.2.3 on 2023-08-04 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="rid",),
        migrations.AddField(
            model_name="image",
            name="review",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="review.review",
            ),
            preserve_default=False,
        ),
    ]
