# Generated by Django 4.2.3 on 2023-08-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="rid", new_name="review",
        ),
    ]
