# Generated by Django 4.2.3 on 2023-08-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_rename_rid_comment_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="actPlace",
            field=models.CharField(default=1, max_length=60, verbose_name="봉사 장소"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="review",
            name="region",
            field=models.CharField(default=1, max_length=30, verbose_name="봉사 지역"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="category",
            field=models.CharField(max_length=60, verbose_name="봉사 태그"),
        ),
        migrations.AlterField(
            model_name="review", name="content", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="progrmRegistNo",
            field=models.CharField(max_length=20, verbose_name="봉사 등록번호"),
        ),
    ]
