# Generated by Django 4.2.3 on 2023-08-13 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("review", "0007_cheered_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="category", new_name="tag",
        ),
        migrations.RemoveField(model_name="review", name="actPlace",),
        migrations.AlterField(
            model_name="comment",
            name="cid",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="댓글 ID"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="댓글 내용"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="댓글 작성자",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_public",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")],
                default=True,
                verbose_name="공개 여부(공개면 True)",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="region",
            field=models.CharField(max_length=30, verbose_name="봉사 지역(시군구 코드)"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rid",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="봉사 ID"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=100, verbose_name="제목"),
        ),
        migrations.AlterField(
            model_name="review",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
    ]
