# Generated by Django 4.2.3 on 2023-08-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0010_review_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="region",
            field=models.CharField(blank=True, max_length=60, verbose_name="구군 코드"),
        ),
    ]
