# Generated by Django 4.2.3 on 2023-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="age",),
        migrations.RemoveField(model_name="user", name="category",),
        migrations.RemoveField(model_name="user", name="region",),
        migrations.AddField(
            model_name="user", name="fighting", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(default=None, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="resol_msg",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
