# Generated by Django 4.2.3 on 2023-08-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_resol_msg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fighting",
            field=models.IntegerField(default=0, verbose_name="파이팅 지수"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                default=None, upload_to="", verbose_name="구글 프로필 이미지"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="resol_msg",
            field=models.CharField(max_length=100, verbose_name="다짐 메세지"),
        ),
    ]
