name: DowaDream CI/CD

on: # action을 언제 실행할지 설정
  push:
    branches: ["feat/#3-cicd"]

jobs:
  CI:
    name: 'CI'
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4 # 병렬 처리
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3 # @: github actions 라이브러리(v3) 사용

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate env file
        run: |
          echo "$ENV_FILE" >> .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Run Tests
        run: |
          python manage.py test
